### PR TITLE
Fix Japanese translation

### PR DESCRIPTION
**Pull request by AndroPlus-org**
Japanese translation was completely broken and I fixed it.
I want to fix two strings:
"Shutdown complete, press home to exit"
"It is OK to be straight"
, but it seems there is no string key for them.

### CODE REVIEW

**Comment by blawar** [comment]
How was the japanese translation broken?  I pushed a new json file with the new keys.

**Comment by blawar** [comment]
I went ahead and manually merged your changes, since the PR could not be merged easily from the web.

**Comment by blawar** [comment]
thanks for your help.

**Comment by AndroPlus-org** [comment]
Thank you!

Most translations were machine translated and it was hard to understand for natives.
I updated new keys:
https://github.com/blawar/translations/pull/20

**Pull request closed without merging**
